var mtn_peaks={
"type": "FeatureCollection",
"name": "",
"coordinates": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "TITLE": "Bowler", "TITLE_2": "Collision/Trauma", "TITLE_3": "Hit by car", "TITLE_4": "Treated", "VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "number_of_": 31, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -88.75996, 44.87216 ] } },
{ "type": "Feature", "properties": { "TITLE": "Boscobel", "TITLE_2": "Lead Poisoned", "TITLE_3": "lead poisoning", "TITLE_4": "Died in care","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 8516, "number_of_": 9, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -90.71704, 43.51821 ] } },
{ "type": "Feature", "properties": { "TITLE": "Monroe", "TITLE_2": "Collision/Trauma", "TITLE_3": "Hit by car", "TITLE_4": "Treated","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 8850, "number_of_": 172, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -89.64632, 42.79958 ] } },
{ "type": "Feature", "properties": { "TITLE": "Munising", "TITLE_2": "External trauma", "TITLE_3": "territorial fight", "TITLE_4": "Released","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 8485, "number_of_": 30, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -86.642529, 46.350590 ] } },
{ "type": "Feature", "properties": { "TITLE": "Hayward", "TITLE_2": "Indeterminate", "TITLE_3": "starving", "TITLE_4": "Died in care","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 8188, "number_of_": 3, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -91.785733, 45.740299 ] } },
{ "type": "Feature", "properties": { "TITLE": "Ojibwa", "TITLE_2": "Indeterminate", "TITLE_3": "Starving", "TITLE_4": "Released","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 8167, "number_of_": 57, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -91.11726, 45.79918 ] } },
{ "type": "Feature", "properties": { "TITLE": "Casper Lake", "TITLE_2": "External trauma", "TITLE_3": "wing injury", "TITLE_4": "Released","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 8163, "number_of_": 53, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -91.50890, 46.15268 ] } },
{ "type": "Feature", "properties": { "TITLE": "Independence", "TITLE_2": "Lead Poisoned", "TITLE_3": "starving", "TITLE_4": "Died in care","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 8163, "number_of_": 53, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -91.44739, 44.53365 ] } },

    


{ "type": "Feature", "properties": { "TITLE": "Sauk County", "TITLE_2": "Indeterminate", "TITLE_3": "Referred from a non-permitted animal care facility", "TITLE_4": "Euthanized","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7937, "number_of_": 6, "number_of1": 3 }, "geometry": { "type": "Point", "coordinates": [ -89.753597, 43.552243 ] } },
{ "type": "Feature", "properties": { "TITLE": "Vernon County", "TITLE_2": "Collision/Trauma", "TITLE_3": "Collision with a car, truck or motorcycle", "TITLE_4": "Died","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7643, "number_of_": 1, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -90.918692, 43.605815 ] } },
{ "type": "Feature", "properties": { "TITLE": "Iowa County", "TITLE_2": "Collision/Trauma", "TITLE_3": "Collision with a car, truck or motorcycle", "TITLE_4": "Euthanized","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7751, "number_of_": 3, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -90.11349, 43.09073 ] } },
{ "type": "Feature", "properties": { "TITLE": "Lafayette County", "TITLE_2": "Collision/Trauma", "TITLE_3": "Collision with a car, truck or motorcycle", "TITLE_4": "Euthanized","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7710, "number_of_": 8, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -90.165080, 42.647135 ] } },
{ "type": "Feature", "properties": { "TITLE": "Columbia County", "TITLE_2": "Collision/Trauma", "TITLE_3": "Collision with a car, truck or motorcycle", "TITLE_4": "Transferred","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7678, "number_of_": 12, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -89.296469, 43.435431 ] } },
{ "type": "Feature", "properties": { "TITLE": "Grant County", "TITLE_2": "Collision/Trauma", "TITLE_3": "Collision with a car, truck or motorcycle", "TITLE_4": "Died","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7647, "number_of_": 3, "number_of1": 3 }, "geometry": { "type": "Point", "coordinates": [ -90.832741, 42.749623 ] } },

{ "type": "Feature", "properties": { "TITLE": "Vilas County", "TITLE_2": "Lead Poisoned", "TITLE_3": "Shoulder Injury", "TITLE_4": "Released","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7618, "number_of_": 4, "number_of1": 9 }, "geometry": { "type": "Point", "coordinates": [ -89.502724, 46.045593 ] } },
{ "type": "Feature", "properties": { "TITLE": "Oneida County", "TITLE_2": "External trauma", "TITLE_3": "Shoulder Injury", "TITLE_4": "Treated","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7583, "number_of_": 0, "number_of1": 3 }, "geometry": { "type": "Point", "coordinates": [ -89.754754, 45.676257 ] } },
{ "type": "Feature", "properties": { "TITLE": "Lincoln County", "TITLE_2": "External trauma", "TITLE_3": "wing injury", "TITLE_4": "Treated","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7555, "number_of_": 8, "number_of1": 2 }, "geometry": { "type": "Point", "coordinates": [ -89.850930, 45.350088 ] } },
{ "type": "Feature", "properties": { "TITLE": "Sawyer County", "TITLE_2": "External trauma", "TITLE_3": "wing injury", "TITLE_4": "Released","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7540, "number_of_": 0, "number_of1": 4 }, "geometry": { "type": "Point", "coordinates": [ -91.073380, 45.938806 ] } },
{ "type": "Feature", "properties": { "TITLE": "Washburn County", "TITLE_2": "External trauma", "TITLE_3": "wing injury", "TITLE_4": "Died in care","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7525, "number_of_": 4, "number_of1": 4 }, "geometry": { "type": "Point", "coordinates": [ -91.752887, 45.866204 ] } },
{ "type": "Feature", "properties": { "TITLE": "Florence County", "TITLE_2": "Indeterminate", "TITLE_3": "Shoulder Injury", "TITLE_4": "Treated","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7485, "number_of_": 0, "number_of1": 2 }, "geometry": { "type": "Point", "coordinates": [ -88.536210, 45.835579 ] } },
{ "type": "Feature", "properties": { "TITLE": "Ashland County", "TITLE_2": "External trauma", "TITLE_3": "wing injury", "TITLE_4": "Released","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7455, "number_of_": 8, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -90.832925, 46.273372 ] } },
{ "type": "Feature", "properties": { "TITLE": "Burnett County", "TITLE_2": "Internal trauma", "TITLE_3": "Shoulder Injury", "TITLE_4": "Released","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7371, "number_of_": 1, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -92.519764, 45.865228 ] } },
{ "type": "Feature", "properties": { "TITLE": "Barron County", "TITLE_2": "Indeterminate", "TITLE_3": "Spinal Injury", "TITLE_4": "Treated","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7371, "number_of_": 3, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -91.971942, 45.362684 ] } },
{ "type": "Feature", "properties": { "TITLE": "Price County", "TITLE_2": "Indeterminate", "TITLE_3": "Spinal Injury", "TITLE_4": "Treated","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7365, "number_of_": 0, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -90.243131, 45.711199 ] } },

{ "type": "Feature", "properties": { "TITLE": "Dunn County", "TITLE_2": "Toxicity", "TITLE_3": "Animal Interaction", "TITLE_4": "Died","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7351, "number_of_": 0, "number_of1": 2 }, "geometry": { "type": "Point", "coordinates": [ -91.972060, 44.991297 ] } },
{ "type": "Feature", "properties": { "TITLE": "Buffalo County", "TITLE_2": "Indeterminate", "TITLE_3": "Indeterminate", "TITLE_4": "Died","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7350, "number_of_": 3, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -91.773187, 44.523906 ] } },
{ "type": "Feature", "properties": { "TITLE": "Eau Claire", "TITLE_2": "Indeterminate", "TITLE_3": "Indeterminate", "TITLE_4": "Died","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 5, "number_of_": 2, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -91.497080, 44.854408 ] } },
{ "type": "Feature", "properties": { "TITLE": "Pierce County", "TITLE_2": "Toxicity", "TITLE_3": "Indeterminate", "TITLE_4": "Died","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7321, "number_of_": 0, "number_of1": 6 }, "geometry": { "type": "Point", "coordinates": [ -92.480037, 44.666949 ] } },
{ "type": "Feature", "properties": { "TITLE": "Trempealeau County", "TITLE_2": "Toxicity", "TITLE_3": "Indeterminate", "TITLE_4": "Died","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7264, "number_of_": 0, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -91.378274, 44.402581 ] } },
{ "type": "Feature", "properties": { "TITLE": "Chippewa County", "TITLE_2": "External Injury", "TITLE_3": "Habitat Destruction", "TITLE_4": "Released","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7227, "number_of_": 15, "number_of1": 4 }, "geometry": { "type": "Point", "coordinates": [ -91.283542, 45.197161 ] } },
{ "type": "Feature", "properties": { "TITLE": "Marathon County", "TITLE_2": "Indeterminate", "TITLE_3": "Indeterminate", "TITLE_4": "Died","VISIBLE": 1, "DESCRIPTIO": null, "DATE": null, "TYPEID": 0, "Peak_Heigh": 7219, "number_of_": 6, "number_of1": 1 }, "geometry": { "type": "Point", "coordinates": [ -89.962612, 45.055428 ] } },


]
};


